[profile.default]
src = "src"
libs = ["lib"]
# libs = ["dependencies"]
out = "build/abis"
# out = "build/artifacts"
cache_path = "build/cache"
build_info = true
build_info_path = "build/build-info"
remappings = [
    '@forge-std=lib/forge-std/',
    '@openzeppelin=lib/openzeppelin-contracts/',
    '@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable'
]

gas_reports = ['*']
fs_permissions = [{ access = "read-write", path = "./" }]
ffi = true
no-match-contract = "FFI"
optimizer = true
optimizer_runs = 200
via_ir = false
# solc_version = '0.8.20'
auto_detect_solc = true

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4


[profile.dev]
eth_rpc_url="http://127.0.0.1:8545"
chain_id=9527


[profile.testnet]
eth_rpc_url="https://rpc.sepolia.org"
chain_id=11155111


[profile.mainnet]
eth_rpc_url="http://127.0.0.1:8545"
chain_id=1


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
